### ISSUE TITLE
Dropdown toggle isn't clickable

### ISSUE THREAD

**Issue by RobertKorteland** [SocialSchools/socialschools-cms#78]
I introduced this dropdown menu for KSU. however, although the submenu items are clickable, the main menu item no longer is. So you can't visit the "onze school" main page now.

![screen shot 2015-04-03 at 13 12 32](https://cloud.githubusercontent.com/assets/2690692/6981525/253c661a-da03-11e4-8bb4-093479268b76.png)

**Comment by vinitkumar** [comment]
The issue is with the library itself. We either need to patch the library or find another library.

**Comment by vinitkumar** [comment]
Fixing this in multitenant-cms.
