### ISSUE TITLE
CSS broken

### ISSUE THREAD

**Issue by crazyscorpio12** [SocialSchools/socialschools-cms#86]
http://vsodehogebrug.cms.socialschools.nl/contact/

![screen shot 2015-07-09 at 1 40 58 pm](https://cloud.githubusercontent.com/assets/73951/8590667/58f1a2f2-2640-11e5-8def-fe432c336681.png)

cc: @RobertKorteland

**Comment by RobertKorteland** [comment]
Fixed in multitenant CMS
